version: 2.1
jobs:
  build-and-deploy:
    macos:
      xcode: "11.5"
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: |
	    curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
	    pod install
