version: 2.1
workflow:
  jobs:
    build-and-deploy:
      macos:
        xcode: 11.5
      steps:
        - checkout
        - run:
            name: Install CocoaPods
            command: pod install
